backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/images/uploads" # Media files will be stored in the repo under public/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "projects" # Used in routes, e.g., /admin/collections/blog
    label: "Projects" # Used in the UI
    folder: "content/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Status", name: "status", widget: "select", options: ["ACTIVE", "ARCHIVED", "PENDING", "COMPLETED", "UNKNOWN"] }
      - { label: "Main Image", name: "mainImage", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
